import type { Metadata } from 'next'
import React from "react";

export const metadata: Metadata = {
  title: 'logIn',
  description: 'Generated by create next app',
}

export default function Layout({children}: {children: React.ReactNode}) {
  return (
      <>
          {children}
      </>
  )
}
